<<<<<<< HEAD
spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/itogether?serverTimezone=Asia/Seoul
    username: root
    password: kang165
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
=======
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itogether?serverTimezone=Asia/Seoul
    username: **
    password: **
    driver-class-name: com.mysql.cj.jdbc.Driver

  mybatis:
    config-location: classpath*:mybatis-config.xml
    mapper-location: classpath*:mapper/*.xml
    type-aliases-package: com.itmo.itogether.Domain
>>>>>>> develop
