spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/itogether?serverTimezone=Asia/Seoul
    username: root
    password: kang165
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy